User can compare stats with another user.
hermansenph/rocket-league-stats pull request #11
Opened 2017-09-18 20:40 UTC by hermansenph

![user can compare](https://user-images.githubusercontent.com/31448931/30563507-f1f93876-9c76-11e7-813d-54161415714b.gif)

2017-09-18 20:49 UTC, thebearingedge approved these changes
Will it be possible to remove a player from the comparison?

2017-09-18 23:24 UTC, hermansenph commented
User can now remove players that were previously compared.

2017-09-18 23:26 UTC, thebearingedge requested changes

2017-09-18 23:26 UTC, thebearingedge commented on main.js
> +  element.className -= ' hidden'
Does this actually work?

2017-09-19 16:45 UTC, thebearingedge commented on main.js
> +  element.className -= ' hidden'
It might give you the result you want, but I don't think it's doing what you expected.

2017-09-19 16:45 UTC, thebearingedge commented
Please reopen when ready.

2017-09-19 17:30 UTC, thebearingedge approved these changes

2017-09-19 18:08 UTC, merged